services:
  axon-server:
    image: axoniq/axonserver:2023.2.0-jdk-17
    ports:
      - 8024:8024
      - 8124:8124

#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  watchlist-view-db:
    image: postgres:14
    environment:
      POSTGRES_DB: investing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mhsatuck
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "3032:5432"
volumes:
  postgres: