axoniq:
  console:
    credentials: 5fd32c85-0:bf1b0c38f851447fad1951aa3ceb12fc

server:
  port: 3030
logging:
  level:
    web: info


spring:
  r2dbc:
    username: postgres
    password: mhsatuck
    url: r2dbc:postgresql://localhost:3032/investing
  liquibase:
    url: jdbc:postgresql://localhost:3032/investing
    change-log: classpath:db/changelog/changelog-master.xml
    user: postgres
    password: mhsatuck
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update