axoniq:
  console:
    credentials: 5fd32c85-0:bf1b0c38f851447fad1951aa3ceb12fc

axon:
  amqp:
    exchange: ex.watchlist.events

server:
  port: 3030
logging:
  level:
    web: info


spring:
  datasource:
    dbcp2:
      username: postgres
      password: mhsatuck
      url: jdbc:postgresql://localhost:3032/investing
      driver-class-name: org.postgresql.Driver
