spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

axon:
  serializer:
    general: xstream
    messages: xstream
    events: jackson
  axonserver:
    context: investing