/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.qstudio.investing.watchlist

import com.qstudio.investing.watchlist.infrastructure.configuration.AxonConfig
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer
import org.springframework.context.annotation.Import
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories

@SpringBootApplication
@EnableR2dbcRepositories
@Import(AxonConfig::class)
class WatchlistApp : SpringBootServletInitializer()

fun main(args: Array<String>) {
    SpringApplication.run(WatchlistApp::class.java, *args)
}
