/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.qstudio.investing.watchlist

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer

@SpringBootApplication
class WatchlistApp : SpringBootServletInitializer()

fun main(args: Array<String>) {
    SpringApplication.run(WatchlistApp::class.java, *args)
}
