axoniq:
  console:
    credentials: 5fd32c85-0:bf1b0c38f851447fad1951aa3ceb12fc


server:
  port: 3031
logging:
  level:
    web: info

app:
  messageBus:
    type: axon

spring:
  profiles:
    active: ${app.messageBus.type}
  r2dbc:
    username: postgres
    password: mhsatuck
    url: r2dbc:postgresql://localhost:3032/investing
  liquibase:
    url: jdbc:postgresql://localhost:3032/investing
    change-log: classpath:db/changelog/changelog-master.xml
    user: postgres
    password: mhsatuck
    enabled: true
  datasource:
    dbcp2:
      username: postgres
      password: mhsatuck
      url: jdbc:postgresql://localhost:3032/investing
      driver-class-name: org.postgresql.Driver
