spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

axon:
  serializer:
    general: jackson
    messages: jackson
    events: jackson
  axonserver:
    context: investing